version: '3'

services:
  pg:
    container_name: ${CONTAINER_NAME}
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
